# Generated by Django 5.2.5 on 2025-08-29 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Xã', 'Xã'), ('Phường', 'Phường'), ('Thị Trấn', 'Thị Trấn')], default='Xã', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CommuneOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Xã', 'Xã'), ('Phường', 'Phường'), ('Thị Trấn', 'Thị Trấn')], default='Xã', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Huyện', 'Huyện'), ('Thành Phố', 'Thành Phố'), ('Thị Xã', 'Thị Xã'), ('Quận', 'Quận')], default='Huyện', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Tỉnh', 'Tỉnh'), ('Thành Phố', 'Thành Phố')], default='Tỉnh', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Tỉnh', 'Tỉnh'), ('Thành Phố', 'Thành Phố')], default='Tỉnh', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(auto_now_add=True)),
                ('commune_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.communenew')),
                ('commune_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.communeold')),
            ],
        ),
        migrations.AddField(
            model_name='communeold',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.district'),
        ),
        migrations.AddField(
            model_name='communenew',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.provincenew'),
        ),
        migrations.CreateModel(
            name='ProvinceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(auto_now_add=True)),
                ('province_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.provincenew')),
                ('province_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.provinceold')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.provinceold'),
        ),
        migrations.AddField(
            model_name='communeold',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.provinceold'),
        ),
    ]
