# Generated by Django 5.2.5 on 2025-08-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeHistory',
            new_name='CommuneHistory',
        ),
        migrations.DeleteModel(
            name='ProvinceHistory',
        ),
    ]
