# Generated by Django 5.2.5 on 2025-08-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_rename_changehistory_communehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communenew',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='communenew',
            unique_together={('name', 'province')},
        ),
    ]
