# Generated by Django 5.2.5 on 2025-08-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_communenew_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communeold',
            name='province',
        ),
    ]
